services:
  db:
    build: ./postgre
    container_name: pashield_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./postgre/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - .env
    networks:
      - pashield_network

  adminer:
    container_name: pashield_db_adminer
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8083:8080"
    networks:
      - pashield_network

networks:
  pashield_network:
    driver: bridge
    name: pashield_network